src/EnglishNow.Web/Models/Aluno/EditarViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EnglishNow.Web.Models.Aluno
{
    public class EditarViewModel
    {
        public int Id { get; set; }

        public int UsuarioId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        public string? Login { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        public string? Senha { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        public string? Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        public string? Email { get; set; }
    }
}

src/EnglishNow.Web/Models/Boletim/EditarViewModel.cs
namespace EnglishNow.Web.Models.Boletim
{
    public class EditarViewModel
    {
        public int BoletimId { get; set; }

        public int TurmaId { get; set; }

        public string? NomeAluno { get; set; }

        public string? DescricaoTurma { get; set; }

        public decimal? NotaBim1Escrita { get; set; }

        public decimal? NotaBim1Leitura { get; set; }

        public decimal? NotaBim1Conversacao { get; set; }

        public decimal? NotaBim1Final { get; set; }

        public decimal? NotaBim2Escrita { get; set; }

        public decimal? NotaBim2Leitura { get; set; }

        public decimal? NotaBim2Conversacao { get; set; }

        public decimal? NotaBim2Final { get; set; }

        public decimal? NotaFinalSemestre { get; set; }

        public int? FaltasSemestre { get; set; }

        public bool PermitirEdicao { get; set; }
    }
}

src/EnglishNow.Web/Models/Professor/EditarViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EnglishNow.Web.Models.Professor
{
    public class EditarViewModel
    {
        public int Id { get; set; }

        public int UsuarioId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        public string? Login { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        public string? Senha { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        public string? Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        public string? Email { get; set; }

        public IList<TurmasProfessorViewModel>? TurmasProfessor { get; set; }

    }

    public class TurmasProfessorViewModel
    {
        public int Id { get; set; }
        public string? Nivel { get; set; }
        public string? Periodo { get; set; }
        public int Ano { get; set; }
        public int Semestre { get; set; }
    }
}

src/EnglishNow.Web/Models/Turma/EditarViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace EnglishNow.Web.Models.Turma
{
    public class EditarViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo ano é obrigatório")]
        public required int Ano { get; set; }

        [Required(ErrorMessage = "O campo semestre é obrigatório")]
        public required int Semestre { get; set; }

        [Required(ErrorMessage = "O campo professor é obrigatório")]
        public int ProfessorId { get; set; }

        [Required(ErrorMessage = "O campo nivel é obrigatório")]
        public required string Nivel { get; set; }

        [Required(ErrorMessage = "O campo periodo é obrigatório")]
        public required string Periodo { get; set; }

        public List<SelectListItem>? Semestres { get; set; }

        public List<SelectListItem>? Professores { get; set; }

        public IList<AlunoTurmaViewModel>? AlunosTurma { get; set; }

        public IList<AlunoTurmaViewModel>? Alunos { get; set; }

        public bool PodeEditarApagarTurma { get; set; }

    }

    public class AlunoTurmaViewModel
    {
        public int Id { get; set; }

        public required string Nome { get; set; }

        public required string Email { get; set; }

        public required string Login { get; set; }
    }
}

src/EnglishNow.Web/Controllers/BoletimController.cs
using EnglishNow.Services;
using EnglishNow.Web.Mappings;
using EnglishNow.Web.Models.Boletim;
using Microsoft.AspNetCore.Mvc;

namespace EnglishNow.Web.Controllers
{
    [Route("boletim")]
    public class BoletimController : Controller
    {
        private readonly IBoletimService _boletimService;

        public BoletimController(IBoletimService boletimService)
        {
            _boletimService = boletimService;
        }

        [Route("editar/{alunoId}/{turmaId}")]
        public IActionResult Editar(int alunoId, int turmaId)
        {
            var result = _boletimService.ObterBoletimPorAlunoTurma(alunoId, turmaId);

            if (result == null)
            {
                return RedirectToAction("Editar", "Turma", new { id = turmaId });
            }

            var model = result.MapToEditarViewModel();

            model.PermitirEdicao = User.IsInRole("Administrador") || User.IsInRole("Professor");

            return View(model);
        }

        [HttpPost]
        [Route("editar/{alunoId}/{turmaId}")]
        public IActionResult Editar(EditarViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var request = model.MapToAtualizarBoletimRequest();

            var result = _boletimService.Atualizar(request);

            if (!result.Sucesso)
            {
                ModelState.AddModelError(string.Empty, result.MensagemErro!);

                return View(model);
            }

            return RedirectToAction("Editar", "Turma", new { id = model.TurmaId } );
        }
    }
}

src/EnglishNow.Web/Views/Boletim/Editar.cshtml
@using EnglishNow.Web.Models.Menu
@using System.Globalization

@model EnglishNow.Web.Models.Boletim.EditarViewModel
@{
    ViewData["Title"] = "Editar boletim - ";

    ViewData["Menu"] = Menu.Turma;
}

<h1>Editar turma</h1>

<p>Turma: @Model.DescricaoTurma</p>

<p>Aluno: @Model.NomeAluno</p>

<form class="needs-validation" asp-controller="Boletim" asp-action="Editar" novalidate>
    <input type="hidden" asp-for="BoletimId" />
    <div class="card border my-3">
        <div class="card-header">
            <h4>1° bimestre</h4>
        </div>
        <div class="card-body">
            <div class="row gx-2 gy-3">
                <div class="col-sm-12 col-md-3">
                    <label>Escrita (0-10)</label>
                    <input type="number" id="notaBim1Escrita" disabled=@(Model.PermitirEdicao ? null : "disabled") class="form-control calcular1" step="any" placeholder="--" maxlength="3" min="0" max="10" asp-for="NotaBim1Escrita" />
                </div>
                
                <div class="col-sm-12 col-md-3">
                    <label>Leitura (0-10)</label>
                    <input type="number" id="notaBim1Leitura" disabled=@(Model.PermitirEdicao ? null : "disabled") class="form-control calcular1" step="any" placeholder="--" maxlength="3" min="0" max="10" asp-for="NotaBim1Leitura" />
                </div>

                <div class="col-sm-12 col-md-3">
                    <label>Conversação (0-10)</label>
                    <input type="number" id="notaBim1Conversacao" disabled=@(Model.PermitirEdicao ? null : "disabled") class="form-control calcular1" step="any" placeholder="--" maxlength="3" min="0" max="10" asp-for=NotaBim1Conversacao>
                </div>
            </div>

            <p class="m-0 pt-3">Nota Final 1° Bimestre: <b id="notaBim1FinalExibicao">@(Model.NotaBim1Final.HasValue? Model.NotaBim1Final: String.Empty)</b></p>
            <input type="hidden" asp-for="NotaBim1Final" id="notaBim1Final">
        </div>
    </div>

    <div class="card border my-3">
        <div class="card-header">
            <h4>2° bimestre</h4>
        </div>
        <div class="card-body">
            <div class="row gx-2 gy-3">
                <div class="col-sm-12 col-md-3">
                    <label>Escrita (0-10)</label>
                    <input type="number" id="notaBim2Escrita" disabled=@(Model.PermitirEdicao ? null : "disabled") class="form-control calcular2" step="any" placeholder="--" maxlength="3" min="0" max="10" asp-for="NotaBim2Escrita" />
                </div>

                <div class="col-sm-12 col-md-3">
                    <label>Leitura (0-10)</label>
                    <input type="number" id="notaBim2Leitura" disabled=@(Model.PermitirEdicao ? null : "disabled") class="form-control calcular2" step="any" placeholder="--" maxlength="3" min="0" max="10" asp-for="NotaBim2Leitura" />
                </div>

                <div class="col-sm-12 col-md-3">
                    <label>Conversação (0-10)</label>
                    <input type="number" id="notaBim2Conversacao" disabled=@(Model.PermitirEdicao ? null : "disabled") class="form-control calcular2" step="any" placeholder="--" maxlength="3" min="0" max="10" asp-for="NotaBim2Conversacao">
                </div>
            </div>

            <p class="m-0 pt-3">Nota Final 2° Bimestre: <b id="notaBim2FinalExibicao">@(Model.NotaBim2Final.HasValue? Model.NotaBim2Final: String.Empty)</b></p>
            <input type="hidden" asp-for="NotaBim2Final"  id="notaBim2Final">
        </div>
    </div>

    <div class="card border my-3">
        <div class="card-header">
            <h4>Nota Final e Faltas</h4>
        </div>
        <div class="card-body">
            <div class="row gx-2 gy-3">
                <div class="col-sm-12 col-md-3 my-3">
                    <label>Faltas</label>
                    <input type="number" disabled=@(Model.PermitirEdicao ? null : "disabled") class="form-control" step="any" placeholder="--" maxlength="3" asp-for="FaltasSemestre">
                </div>

                <p class="m-0">Nota Final: <b id="notaFinalExibicao">@(Model.NotaFinalSemestre.HasValue ? Model.NotaFinalSemestre.Value : string.Empty)</b></p>
                <input type="hidden" asp-for="NotaFinalSemestre" id="notaFinal"/>
            </div>
        </div>
    </div>

    @if (Model.PermitirEdicao)
    {
        <div>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    }
    
</form>

@section Scripts {
    <script>
         (() => {
          'use strict'

          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          const forms = document.querySelectorAll('.needs-validation')

          // Loop over them and prevent submission
          Array.from(forms).forEach(form => {
            form.addEventListener('submit', event => {
              if (!form.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
              }

              form.classList.add('was-validated')
            }, false)
          })
        })()

        const elementosBim1 = document.getElementsByClassName('calcular1');
        const elementosBim2 = document.getElementsByClassName('calcular2');

        //bim1
        const elementoNotaBim1Escrita = document.getElementById('notaBim1Escrita');
        const elementoNotaBim1Leitura = document.getElementById('notaBim1Leitura');
        const elementoNotaBim1Conversacao = document.getElementById('notaBim1Conversacao');
        const elementoNotaBim1Final = document.getElementById('notaBim1Final');
        const elementoNotaBim1FinalExibicao = document.getElementById('notaBim1FinalExibicao');

        //bim2
        const elementoNotaBim2Escrita = document.getElementById('notaBim2Escrita');
        const elementoNotaBim2Leitura = document.getElementById('notaBim2Leitura');
        const elementoNotaBim2Conversacao = document.getElementById('notaBim2Conversacao');
        const elementoNotaBim2Final = document.getElementById('notaBim2Final');
        const elementoNotaBim2FinalExibicao = document.getElementById('notaBim2FinalExibicao');

        //nota final
        const elementoNotaFinalExibicao = document.getElementById('notaFinalExibicao');
        const elementoNotaFinal = document.getElementById('notaFinal');

        let notaBim1Final = @(Model.NotaBim1Final.HasValue ? Model.NotaBim1Final.Value.ToString(CultureInfo.InvariantCulture) : 0);
        let notaBim2Final = @(Model.NotaBim2Final.HasValue? Model.NotaBim2Final.Value.ToString(CultureInfo.InvariantCulture) : 0);

        const calcularNotaBim1 = function()
        {
            if (elementoNotaBim1Escrita.value === '' ||
            elementoNotaBim1Leitura.value === '' ||
            elementoNotaBim1Conversacao.value === '')
            {
                elementoNotaBim1FinalExibicao.innerText = '';
                elementoNotaBim1Final.value = '';
                elementoNotaFinalExibicao.innerText = '';
                elementoNotaFinal.value = '';

                return;
            }

            const notaBim1Escrita = +elementoNotaBim1Escrita.value;
            const notaBim1Leitura = +elementoNotaBim1Leitura.value;
            const notaBim1Conversacao = +elementoNotaBim1Conversacao.value;

            notaBim1Final = calcularMediaBimestre(notaBim1Escrita, notaBim1Leitura, notaBim1Conversacao);

            elementoNotaBim1FinalExibicao.innerText = notaBim1Final.toLocaleString('pt-BR');
            elementoNotaBim1Final.value = notaBim1Final.toLocaleString('pt-BR');

            calcularNotaFinal();
        }

        const calcularNotaBim2 = function()
        {
            if (elementoNotaBim2Escrita.value === '' ||
            elementoNotaBim2Leitura.value === '' ||
            elementoNotaBim2Conversacao.value === '')
            {
                elementoNotaBim2FinalExibicao.innerText = '';
                elementoNotaBim2Final.value = '';
                elementoNotaFinalExibicao.innerText = '';
                elementoNotaFinal.value = '';


                return;
            }

            const notaBim2Escrita = +elementoNotaBim2Escrita.value;
            const notaBim2Leitura = +elementoNotaBim2Leitura.value;
            const notaBim2Conversacao = +elementoNotaBim2Conversacao.value;

            notaBim2Final = calcularMediaBimestre(notaBim2Escrita, notaBim2Leitura, notaBim2Conversacao);

            elementoNotaBim2FinalExibicao.innerText = notaBim2Final.toLocaleString('pt-BR');
            elementoNotaBim2Final.value = notaBim2Final.toLocaleString('pt-BR');

            calcularNotaFinal();
        }

        for (let i = 0; i < elementosBim1.length; i++)
        {
            elementosBim1[i].addEventListener('keyup', calcularNotaBim1, false);
        }

        for (let i = 0; i < elementosBim2.length; i++)
        {
            elementosBim2[i].addEventListener('keyup', calcularNotaBim2, false);
        }

        function calcularNotaFinal()
        {
            if (elementoNotaBim1FinalExibicao.innerText === '' ||
            elementoNotaBim2FinalExibicao.innerText === '')
            {
                elementoNotaFinalExibicao.innerText = '';
                elementoNotaFinal.value = '';

                return;
            }

            const notaFinal = calcularMediaSemestre(notaBim1Final, notaBim2Final);

            elementoNotaFinalExibicao.innerText = notaFinal.toLocaleString('pt-BR');
            elementoNotaFinal.value = notaFinal.toLocaleString('pt-BR');
        }

        function calcularMediaBimestre(nota1, nota2, nota3)
        {
            const media = (nota1 + nota2 + nota3) / 3;

            return +media.toFixed(2);
        }

        function calcularMediaSemestre(nota1, nota2)
        {
            const media = (nota1 + nota2) / 2;

            return +media.toFixed(2);
        }
    </script>
}