src/EnglishNow.Web/Components/MenuViewComponent.cs
using EnglishNow.Web.Models.Menu;
using Microsoft.AspNetCore.Mvc;

namespace EnglishNow.Web.Components
{
    public class MenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var menu = new MenuViewModel
            {
                Ativo = ViewData["Menu"] as Menu? ?? Menu.Home,
                MenuProfessorVisivel = User.IsInRole("Administrador")
            };

            return View(menu);
        }
    }
}

src/EnglishNow.Web/Controllers/ProfessorController.cs
using EnglishNow.Services;
using EnglishNow.Services.Models.Professor;
using EnglishNow.Web.Mappings;
using EnglishNow.Web.Models.Professor;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnglishNow.Web.Controllers
{
    [Route("professor")]
    [Authorize(Roles = "Administrador")]

    public class ProfessorController : Controller
    {
        private readonly IProfessorService _professorService;
        private readonly ITurmaService _turmaService;
        public ProfessorController(IProfessorService professorService, ITurmaService turmaService)
        {
            _professorService = professorService;

            _turmaService = turmaService;
        }

        [Route("criar")]
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [Route("criar")]
        public IActionResult Criar(CriarViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //cria o professor

            var result = _professorService.Criar(model.MapToCriarProfessorRequest());
            

            if (!result.Sucesso)
            {
                ModelState.AddModelError(string.Empty, result.MensagemErro!);

                return View(model);
            }

            return RedirectToAction("Listar");
        }

        [Route("listar")]
        public IActionResult Listar()
        {
            var professores = _professorService.Listar();

            var result = professores.Select(c => c.MapToListarViewModel()).ToList();

            return View(result);
        }

        [Route("editar/{id}")]
        public IActionResult Editar(int id)
        {
            var professor = _professorService.ObterPorId(id);

            var model = new EditarViewModel();

            model = professor?.MapToEditarViewModel();

            model!.TurmasProfessor = _turmaService.ListarPorProfessorId(id)
                .Select(t => t.MapToTurmasProfessorViewModel()).ToList();

            return View(model);
        }

        [Route("editar/{id}")]
        [HttpPost]
        public IActionResult Editar(EditarViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var request = model.MapToEditarProfessorRequest();

            var result = _professorService.Editar(request);

            if (!result.Sucesso)
            {
                ModelState.AddModelError(string.Empty, result.MensagemErro!);

                return View(model);
            }

            return RedirectToAction("Listar");

        }

        [Route("excluir/{id}")]
        [HttpPost]
        public IActionResult Excluir(EditarViewModel model)
        {
            var result = _professorService.Excluir(model.Id);

            if (!result.Sucesso)
            {
                TempData["Erro"] = result.MensagemErro;

                return RedirectToAction("Editar", new { id = model.Id });
            }

            return RedirectToAction("Listar");
        }

        public IActionResult Cancelar()
        {
            return RedirectToAction("Listar");
        }
    }
}

src/EnglishNow.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]EnglishNow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EnglishNow.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @await Component.InvokeAsync("Menu")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <p class="col-md-4 mb-0 text-body-secondary">&copy; 2025 Escola de inglês EnglishNow</p>
            <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none" aria-label="Bootstrap">
                <b>EnglishNow</b>
            </a>
            <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item"><a class="nav-link px-2 text-body-secondary" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="nav-item"><a class="nav-link px-2 text-body-secondary" asp-controller="Aluno" asp-action="Listar">Alunos</a></li>
                <li class="nav-item"><a class="nav-link px-2 text-body-secondary" asp-controller="Professor" asp-action="Listar">Professores</a></li>
                <li class="nav-item"><a class="nav-link px-2 text-body-secondary" asp-controller="Turma" asp-action="Listar">Turmas</a></li>
            </ul>
        </footer>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/EnglishNow.Web/Views/Shared/_PublicLayout.cshtml
@{
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] EnglishNow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EnglishNow.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <p class="col-md-4 mb-0 text-body-secondary">&copy; 2025 Escola de inglês EnglishNow</p>
            <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none" aria-label="Bootstrap">
                <b>EnglishNow</b>
            </a>
            <ul class="nav col-md-4 justify-content-end">
                
            </ul>
        </footer>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>